from blog.views.tag_or_category.create import TagOrCategoryCreateView
from blog.views.tag_or_category.delete import TagOrCategoryDeleteView
from blog.views.tag_or_category.post_list_filtered_by_tag import PostListFilteredByTagOrCategory
from blog.views.tag_or_category.update import TagOrCategoryUpdateView
